version: "3"

services:

  db:
    build: db
    ports:
      - 15432:5432
    expose:
      - 5432
    volumes:
      - .docker-compose-volumes/db:/var/lib/postgresql/data

  minio:
    image: minio/minio:edge@sha256:78b6513160ee72794698b808afbeff67b44b510d6d024e0728adc57d726b6c8b
    command:
      - server
      - /data
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
      MINIO_REGION_NAME: us-east-1
    expose:
      - 9000
    ports:
      - 19000:9000
    volumes:
      - .docker-compose-volumes/minio:/data

  server:
    build: .
    environment:
      EXTERNAL_ADDRESS: http://localhost:15000
      BUCKET_NAME: dgp-app
      AWS_ACCESS_KEY_ID: access_key
      AWS_SECRET_ACCESS_KEY: secret_key
      S3_ENDPOINT_URL: http://minio:9000
      GOOGLE_KEY: "${GOOGLE_KEY}"
      GOOGLE_SECRET: "${GOOGLE_SECRET}"
      DATABASE_URL: postgresql://postgres:postgres@db/auth
      DATASETS_DATABASE_URL: postgresql://postgres:postgres@db/datasets
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://postgres:postgres@db/airflow
      ETLS_DATABASE_URL: postgresql://postgres:postgres@db/etls
      AWS_REGION: us-east-1
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
      PUBLIC_KEY_B64: "${PUBLIC_KEY_B64}"
      PRIVATE_KEY_B64: "${PRIVATE_KEY_B64}"
      CKAN_INSTANCE_LOCAL_DEVELOPMENT_API_KEY: "${CKAN_INSTANCE_LOCAL_DEVELOPMENT_API_KEY}"
      CKAN_INSTANCE_LOCAL_DEVELOPMENT_URL: "${CKAN_INSTANCE_LOCAL_DEVELOPMENT_URL}"
    expose:
      - 5000
    ports:
      - 15000:5000
    depends_on:
      - db
      - minio
